### ISSUE TITLE
UI elements and Leaflet Drop Truck

### ISSUE THREAD

**Issue by RohanTLK** [LordGolias/antistasi#1]
So I have never experienced these bugs in about 100 hours of playing the original Antistasi Altis. I also checked their forums to see if this has been mentioned. Thus I assume it is a bug in this fork.

I was hosting from in-game (non dedi) with just 2 people playing.

Firstly, after completing a Leaflet Drop mission and loading up the truck with supplies. Upon bringing the truck back to HQ, the truck neither despawned nor would any of the gear transfer to the ammobox when we selected the 'ammobox transfer' option. 

Second, about 10 seconds after returning to the HQ (probably just after the initial time I selected 'ammobox transfer), all UI elements stopped working. I could bring up the 'Y' menu, for example, but I could not click on any buttons. I could not even click on buttons in my 'esc menu'. I did notice, however, that the option 'skip' was over the top of the option 'save', meaning there might have been some hidden UI pop-up over the top that was hogging screen space. This could have been caused from the initial ammobox transfer'.

**Comment by LordGolias** [comment]
Thanks for pointing this out. This is now fixed in the master.
