### ISSUE TITLE
fnc_BE_refresh is Undefined

### ISSUE THREAD

**Issue by JohnnyDeeee** [LordGolias/antistasi#10]
### My setup:
- Latest arma 3 game/server version
- Dedicated server (setup using TADST)
- Client running on the same pc as the server
- Antistasi (LordGolias edit, master branch) running on Altis
- Default mission parameters

### What happend:
During the creation of a **new** game, the following errors appeared:

> Error in expression 
`<eExec ["fnc_MAINT_arsenal", 2]; [] call fnc_BE_refresh; if ((player == AS_comman>`

> Error position: 
`<fnc_BE_refresh; if ((player == AS_comman>`

> Error Undefined variable in expression: `fnc_be_refresh`

### Steps to reproduce:

1. Start a **dedicated** server
2. Load the Antistasi mission (Altis)
3. Choose 'new game'
3. Look in your client's `.rpt` and notice the errors qouted above

**Comment by LordGolias** [comment]
Fixed in 0f22e5f0b784eae37a3757d550b20665f8bb0c64. Thanks @JohnnyDeeee for the report!
