### ISSUE TITLE
Testing Mines: Leaving mine deploy map sometimes adds mines to arsenal

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#106]
Steps to reproduce:
1-Building Options -> Build Minefield
2-Choose area and place some mines
3-Press escape
4-When building a new minefield more mines can be placed

**P.S. Tested with ACE in the fix_Minefields branch in MP**

**Comment by LordGolias** [comment]
Fixed in fix_minefield branch.
