### ISSUE TITLE
Testing Mines: Mixes different types of AT or AP mines

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#107]
Not sure if on purpose but could it be possible to create mine specific minefields (e.g. AT minefield with M4A1 SLAM mines only)?

**P.S. Tested with ACE in the fix_Minefields branch in MP**

**Comment by LordGolias** [comment]
At the moment they are either AT or AP mines. Why using mine types ("M4A1 SLAM") would make more sense than mines functionality ("AT mine")?
