### ISSUE TITLE
Testing Mines: Mines could be placed inside truck

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#109]
When building minefields, mines used in the minefield could be placed inside truck. Lose truck, lose mines.

**Comment by LordGolias** [comment]
Once the mission is created, the mines are removed from the arsenal. If the truck explodes, the mission fails and the minefield is not built and thus all the mines are lost (and not placed.)

Is this what you mean?

I am closing as won't fix, re-open if you are thinking something different than the above.
