### ISSUE TITLE
Arsenal was wiped out (except backpacks)

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#110]
After saving the game noticed that the arsenal for some reason got wiped. If any help opening the arsenal HUD feature was taking about 30 seconds.

**P.S. Tested with ACE in the fix_Minefields branch in MP**

[Arma3_x64_2017-10-30_10-24-48.txt](https://github.com/LordGolias/antistasi/files/1427661/Arma3_x64_2017-10-30_10-24-48.txt)

**Comment by LordGolias** [comment]
Can you confirm whether this was antistasi related or Arma related?

**Comment by Warhammer47** [comment]
I think I figured it out, seems like I open the arsenal too quickly after load. Seems like I need to wait a few seconds between "Game loaded" hint and actually opening the arsenal. I think it is because the game is still loading all the weapons in the box and I interrupt that process

**Comment by LordGolias** [comment]
great finding! That indeed helps a lot to fix this.

**Comment by LordGolias** [comment]
I believe that 2c18b4ca52cc110149c45e3477e2d06bcd7e6d3a fixes this. It was a race condition being won by accessing the arsenal during load. However, this needs testing before closing. Can you reproduce what you did and check if you can no longer do it?
