### ISSUE TITLE
Destroy antenna .rpt

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#117]
Test done on develop branch SP: https://github.com/LordGolias/antistasi/commit/17ab95a3b4c810e08ec8afaab63e36b292393769

- Mission selection, destroy antenna
10:58:11 "DICT:get([1780381: empty.p3d,""destroy_antenna_roadblock_14580_16386"",""resources""]):ERROR: invalid key"
10:58:11 Error in expression <get) select 0;
[_mission, "resources", [_task, [[], [], [_mrkfin]]]] call AS_spa>
10:58:11   Error position: <_task, [[], [], [_mrkfin]]]] call AS_spa>
10:58:11   Error Undefined variable in expression: _task
10:58:11 File mission\spawns\fnc_destroy_antenna.sqf [AS_mission_fnc_destroy_antenna], line 41

**Comment by LordGolias** [comment]
Thanks Stef! That was indeed an error in the code. Fixed in develop
