### ISSUE TITLE
After mission restart, mission seems 'incomplete'

### ISSUE THREAD

**Issue by JohnnyDeeee** [LordGolias/antistasi#12]
### My setup:
- Latest arma 3 game/server version
- Dedicated server (setup using TADST)
- Client running on the same pc as the server
- Antistasi (LordGolias edit, master branch) running on Altis
- Default mission parameters

### What happend:
After restarting the mission/server, some things are not appearing:

- HQ Items
- Petros
- Most map icons (powerplant still showed after mission restart, but disappeared after server restart)
- The load/create game UI menu
- Start game cinematic

![screenshot_113](https://user-images.githubusercontent.com/9005496/28747597-70616dba-74a3-11e7-9616-34a9274f4707.png)

There are no errors inside the `.rpt log` that have something to do with this issue.

Running admin command `#reassign` after step 8 results in the mission starting as expected (eg. everything is visible again)

### Steps to reproduce:

1. Start a **dedicated** server
2. Load the Antistasi mission (Altis)
3. Choose 'new game'
4. Choose a location
5. Restart the mission (admin command `#restart`)
6. Notice the things mentioned above
(next are optional steps)
7. Restart the server (admin command `#restartserver`)
8. > Notice the things mentioned above

**Comment by LordGolias** [comment]
I finally got time for this. Could you describe here how you set up a dedicated server of antistasi? I would like to know how you did it so I use the same conf to reproduce the issues you found.

For example, what settings you used in TADST?

**Comment by JohnnyDeeee** [comment]
Nothing special for the config. Just set it up as bare as possible.

**Comment by LordGolias** [comment]
Thanks @JohnnyDeeee, I didn't know about the TADST, I am currently testing the init of a dedicated server. :)

**Comment by JohnnyDeeee** [comment]
Findings with current state of master branch (better logging, yay 👍 )

For the 'missing' map icons:

The following errors appear **sometimes** and the referenced locations differ
> "[AS] Error: location_set with wrong location 'AS_resource_6' for property 'spawned'"
> "[AS] Error: location_set with wrong location 'AS_resource_6' for property 'forced_spawned'"

I guess what happens is that once one location fails, the whole script stops and thus the next couple locations do not get processed..

**Comment by JohnnyDeeee** [comment]
And appearently this does not happen only on a restart. I'm still not able to force this behaviour, but i had it a couple times even after a server restart.

**Comment by LordGolias** [comment]
Yes, working on this currently. There is a async issue on which calling 

´´´
X setVariable ["a", 1, true]
y = X getVariable ["a", []]
´´´

sometimes causes y to be []. I am investigating why this is the case, but it seems that setVariable is not a  sync operation in dedicated. My current take on this is to use waitUntil the variable was set correctly

I am investigating this on branch ´init´.

**Comment by JohnnyDeeee** [comment]
Ah i see..
You could do something like this:
`fnc_setVariable = {
    params ["_x", "_name", "_value", "_public"];
    _x setVariable [_name, _value, _public];

    waitUntill {
        (_x getVariable _name) == _value;
    }
}`

(i think.. just woke up :/)

**Comment by LordGolias** [comment]
Fixed in 0f22e5f0b784eae37a3757d550b20665f8bb0c64. Thanks @JohnnyDeeee for the report!
