### ISSUE TITLE
DICTget error 

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#120]
Test done on develop branch SP: https://github.com/LordGolias/antistasi/commit/17ab95a3b4c810e08ec8afaab63e36b292393769

context: moving to do a supplymission, while driving i got this

11:43:25 "DICT:get([1780887: empty.p3d,""as_base_7"",""AAFsupport""]):ERROR: invalid key"

**Comment by LordGolias** [comment]
This is a duplicated of (I though closed) issue #36. Closing this one as duplicated and re-opening the other.
