### ISSUE TITLE
NATO qrf support value

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#121]
Test done on develop branch SP: https://github.com/LordGolias/antistasi/commit/17ab95a3b4c810e08ec8afaab63e36b292393769

- NATO QRF says 10 points but actually require 30. 
https://github.com/LordGolias/antistasi/blob/17ab95a3b4c810e08ec8afaab63e36b292393769/Antistasi/dialogs/manageNATO/dialogs.hpp#L20

https://github.com/LordGolias/antistasi/blob/17ab95a3b4c810e08ec8afaab63e36b292393769/Antistasi/dialogs/manageNATO/fnc_UI_activate.sqf#L67-L69

**Comment by LordGolias** [comment]
Thanks Stef for the fix!
