### ISSUE TITLE
Binoculars removed

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#129]
Version: develop https://github.com/LordGolias/antistasi/commit/8c0ea9bdacffc86ebd00146e22bf80d16e31a147
Mod: CBA, TFAR
Singleplayer & Multiplayer
Faction: against NATO

nothing on RPT but arsenal remove binoculars all the time i take them

**Comment by loxley314** [comment]
Also tested with same result. It's funny in mission savegame it's unlocked.
[savegame_from_clipboard.txt](https://github.com/LordGolias/antistasi/files/1443214/savegame_from_clipboard.txt)
