### ISSUE TITLE
Starting items get added to arsenal even when you choose 'no' [Dedicated server]

### ISSUE THREAD

**Issue by JohnnyDeeee** [LordGolias/antistasi#13]
### My setup:
- Latest arma 3 game/server version
- Dedicated server (setup using TADST)
- Client running on the same pc as the server
- Antistasi (LordGolias edit, master branch) running on Altis
- Default mission parameters

### What happend:
After choosing to start a new game and clicking 'no' when the message 'is this too hard for you' comes up, the Arsenal still contains starting items.

![screenshot_114](https://user-images.githubusercontent.com/9005496/28747660-adac158e-74a4-11e7-90f5-77c3f220f8a2.png)

There are no errors inside the `.rpt log` that have something to do with this issue.

### Steps to reproduce:
1. Start a **dedicated** server
2. Load the Antistasi mission (Altis)
3. Choose 'new game'
4. Choose 'no' when the question 'is this too hard for you' comes up
5. Look in the Arsenal and notice the starting items

**Comment by LordGolias** [comment]
Not sure this is an issue: those items are the default items for starting a mission. The only difference between "easy" and "hard" atm is 

````
AS_Pset("hr",20);
AS_Pset("resourcesFIA",10000);
AS_Pset("prestigeNATO",30);
```
i.e. more hr, resources and NATO support.

Isn't the behavior you are observing equivalent in SP/MP? If not, then yes, we have an issue.

Or maybe the point here is that providing a launcher in the beginning is too much xD

**Comment by JohnnyDeeee** [comment]
Oh i have not really tested this in the other scenarios..

I now that using the official mission (version 1.7.5 beta) on tanoa we started with just a primary and a pistol. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LordGolias** [comment]
So, the suggestion is that easy gives the current setup and hard gives nothing (I. E. Only the unlocked primary and pistol). Is this correct?


If yes, it Sounds like a good idea.

**Comment by JohnnyDeeee** [comment]
Yes that is how i would expect it to behave :)
