### ISSUE TITLE
[Major] Player side error

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#130]
Develop version
Multiplayer 
Fighting against West (vs NATO)

started the server alone
saved game
logged out
logged back in and another player joined

Error = i can't see him in group menu and Petros kill him all the time, if i kill my firend i go to the ocean.

Restarted the game, both logged in, new game, it was working correctly

**Comment by StefArma** [comment]
I tested this when fighting against the east (standard) and petros don't kill the new joining guy, just the guy has no initialization to can't access map info and other addedaction..

I'm wondering if there is something that don't initialize the player

**Comment by LordGolias** [comment]
Any errors on the log file on his side?

**Comment by StefArma** [comment]
is it possible to see? i tought the only valid .rpt when connected to dedicated is the server one

**Comment by StefArma** [comment]
Version: Develop: https://github.com/LordGolias/antistasi/commit/d8d75a59eb7130418757fa755a55716817866bec
Dedicated Server
Mods: None
Faction: against west

again same issue.
If a player join after i initialized the campaign, Petros wanna kill him all the time

found only this
11:32:07 Error a1 reading file 'config\\squads\kom\9okukgvbf0.paa'

**Comment by LordGolias** [comment]
I was able to reproduce this and pushed a potential fix for this. I confirmed that the solution works in non-dedicated MP. This should also solve it in dedicated. Essentially, was a error in initializing JIP clients.

@StefArma, could you double check, and close this if it is solved?

**Comment by StefArma** [comment]
Testing

**Comment by StefArma** [comment]
Fixed
