### ISSUE TITLE
Empty resupply crate

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#135]
Version: develop https://github.com/LordGolias/antistasi/commit/8c0ea9bdacffc86ebd00146e22bf80d16e31a147
Mod: CBA, TFAR
Multiplayer dedicated server
Side: tested both vs East and vs West

Called in esupply t = crate was empty

**Comment by LordGolias** [comment]
This has no information whatsoever on what is the error and how to reproduce it. Please provide more information please.
