### ISSUE TITLE
Undercover status riding vehicle in combat

### ISSUE THREAD

**Issue by loxley314** [LordGolias/antistasi#144]
Just tested in develop version (SP). 
I was engaged in combat, 100 - 200 mt combat range, and entered in a civilian vehicle getting automatically undercover status, I did it repeatedly with same result.
I dunno if there are any log in SP if I can get it (and you explain my how to) I'll copy it next time.

**Comment by StefArma** [comment]
Confirmed both SP and Dedicated server 

version develop

**Comment by LordGolias** [comment]
I agree. So, if a condition A is fulfilled when the player enters the car, the player does not become undercover and the car becomes "reported".

What do you think makes sense for the condition A to be?

**Comment by StefArma** [comment]
In original antistasi is  within 500 m from any enemy... 

A nicer check would be if enemies within 700m has a knowsabout >1.7 

The best would be a LoS check but i think it's too complicated.

**Comment by LordGolias** [comment]
why >1.7? Why not use > 1.5 as in the table in https://community.bistudio.com/wiki/knowsAbout ?
