### ISSUE TITLE
Destroy armor mission: Does not start task

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#153]
**Version: develop
Mods: ACE
Mode: MP**

After accepting the mission, it did not started the task

CODE:

1:23:06 "[AS] 2: new spawn 'destroy_vehicle_as_base_1'"
 1:23:06 "[AS] Server: scheduler_fnc_execute(AS_spawn_fnc_execute):"
 1:23:06 "Worker 2: 38.9254"
 1:23:06 "[AS] 2: spawn 'destroy_vehicle_as_base_1' started state 'initialize'"
 1:23:07 "[AS] 2: spawn 'destroy_vehicle_as_base_1' finished state 'initialize'"
 1:23:07 "[AS] 2: spawn 'destroy_vehicle_as_base_1' started state 'spawn_wait_spawn'"
 1:23:07 "[AS] 2: spawn 'destroy_vehicle_as_base_1' finished state 'spawn_wait_spawn'"
 1:23:07 "[AS] 2: spawn 'destroy_vehicle_as_base_1' started state 'wait_spawn'"

**Comment by LordGolias** [comment]
Does the task appear in the map? Or the task appears but the vehicle is not there?

**Comment by Warhammer47** [comment]
The task does not appear and therefore also not removed from the Petro's
mission list


________________________
     .    .          .     .       <><
    ><>    .    .          .        .     .
   .       .         <><      .         .
____]|[____]|[____|||_|______

Pedro Cardoso Leitão

Estudante da FCUL
Mestrado em Ecologia Marinha

**Comment by LordGolias** [comment]
Then, are you sure that the log that you pasted here is complete? It is strange because the task should have appeared when spawning the "destroy_vehicle_as_base_1" "spawn_wait_spawn".
