### ISSUE TITLE
Crazy Irishman: Weapon buy menu bug

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#155]
**Version: develop
Mods: ACE
Mode: MP**

After completing in  finding the crazy Irishman (aka blackmarket), while trying to buy material noticed that:
- In the menu only the WEAPONS button is redirected to what type and amount of weapons you want the rest (MINES, ACESSORIES and CHARGES) do nothing.
- In the WEAPONS menu buttons did nothing

**Comment by LordGolias** [comment]
Errors in the logs...
