### ISSUE TITLE
Gunner of a technical vehicle is undercover

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#157]
**Version: develop
Mods: ACE
Mode: MP**

When retrieving a technical (camo pickup with mounted .50 cal gun), a car that is always "NOT UNDERCOVER", noticed that if you go to the gunner seat your are undercover

**Comment by LordGolias** [comment]
I believe that this has been fixed in 70d445077f0d9a5080dc5e867749b3c8d3460202 since I cannot reproduce it.

Please re-open if it is not the case. :p
