### ISSUE TITLE
With ACE, enemies sometimes become unconscious but immortals.

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#16]
This happens when you shoot an enemy and it gets unconscious. Often, on the ground, the enemy can be shoot infinitely man times.

Related: https://github.com/acemod/ACE3/issues/839

**Comment by JohnnyDeeee** [comment]
Wasn't there a setting for in the medic module for ace?

**Comment by LordGolias** [comment]
@JohnnyDeeee yes, there is. But we need to make sure it is not an issue on our side of the code first :)

The discussion took off on issue #23, so I will close this one so the discussion is kept in one place.
