### ISSUE TITLE
[minor bug]  ACE & respawn

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#168]
Version: lastest develop https://github.com/LordGolias/antistasi/commit/f75228b2978b05a8d7c7898deafe161d92d2798a
Dedicated server without HeadlessClient
Modset: CBA + TFAR + ACE

When injured and no AI around i've the option to respawn with spacebar but that doesn't work. I can respawn with the Escape respawn tho.

**Comment by Warhammer47** [comment]
already posted:
https://github.com/LordGolias/antistasi/issues/90
