### ISSUE TITLE
[notsure bug] ace_disposable dependency

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#169]
Version: lastest develop https://github.com/LordGolias/antistasi/commit/f75228b2978b05a8d7c7898deafe161d92d2798a
Dedicated server without HeadlessClient
Modset: CBA + TFAR + ACE

21:12:38 soldier[B_soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
21:12:38 soldier[B_soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
21:12:38 soldier[B_soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
21:12:38 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
ace_disposable

I checked the .sqm too and there are no depencencies. however that message display everytime there are certain units spawning.

**Comment by LordGolias** [comment]
Shouldn't having ACE handle the ACE_disposable dependency? I.e. do you have ACE without disposable?

**Comment by StefArma** [comment]
probably all irrelevant now because of major patched from ACE and CBA
