### ISSUE TITLE
Scenario feels more broken and buggy than the original.

### ISSUE THREAD

**Issue by darkshadowguard** [LordGolias/antistasi#175]
Started to play single player when I realized how broken the revive system became, I was only using RHS mods at the time for better weapon selection when I noticed that once downed, you (the player) can revive themselves personally. The enemy AI could also do that as well, just not as frequently.

Became unplayable very fast when the UI vanished and there was not a single option to get it back.. For some reason? It was there in the vanilla version, but it is completely gone. I attempted to use the "fix y button" option but it did not bring back the UI, so it put the nail in the coffin and I stopped playing.

Enemy resistance near resource point was really small and I was surprised, though to be fair I was playing single player and was happy to see it wasn't as ridiculously hard as vanilla, too bad the rest of the experience playing it was awful.

**Comment by LordGolias** [comment]
Thanks for the general feedback. Unfortunately, as it stands, this issue is not actionable. Consider re-phrasing it into more concrete suggestions / issues.
