### ISSUE TITLE
Dedicated server in latest develop

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#177]
Running the latest develop version doesnt work. No New Game/Load Game screen available. The markers on the map initialize but thats about it. No keyboard shortcuts work either.

**Comment by jlillis** [comment]
As of 990bdf16b0922b2fcc625abb76c732fb328b3e33 you need to be the host/logged-in admin to manage savegames - did you log in before starting the mission?

**Comment by SomethingSimpl** [comment]
Yup, logged in before starting

**Comment by jlillis** [comment]
Just got around to confirming this issue on dedicated MP. I'll try looking into it over the weekend.

**Comment by jlillis** [comment]
This issue should be resolved as of 624874237318c196b660800e586a6524cae3eaf8 - can you confirm?

**Comment by SomethingSimpl** [comment]
Yes, the issue seems to be resolved now.
