### ISSUE TITLE
Respawn not working

### ISSUE THREAD

**Issue by LaughMech** [LordGolias/antistasi#179]
I have tried both the develop and master branch version of the mission, using the default Altis mission, running on a dedicated server and with 3 headless clients connected. Logged in as admin before starting the mission, playing commander.

If I go down in an injured state pressing spacebar does not allow me to force respawn. Furthermore if I properly die and respawn at HQ, then the camera moves to hover above my respawned soldier's head with no control, and the camera remains stuck there permanently. Trying to force respawn through the menu kills my soldier and spawns another at HQ, which the camera moves to, but still stays stuck. There is no way to get out of this state except reconnecting.

So far I have never had a respawn work properly (approximately half a dozen attempts).

I would be happy to test further if required - very excited to try this updated version of Antistasi!

**Comment by jlillis** [comment]
I haven't been able to reproduce this on the latest version on the develop branch (31ad8e08de524c1b0f9a19d4901d907c88338178) in multiplayer. Are you running any mods? Are you sure you grabbed the latest version?

**Comment by LaughMech** [comment]
Thanks for checking - I'm afraid this was my mistake. Because I had several versions of this installed at once it looks like I actually simply ran the "master" version of the mission twice when testing, instead of running the "develop" mission also.

Testing the develop version in singleplayer respawns do indeed seem to be working fine; unfortunately I cannot test on my dedicated server due to issue 177, where the mission doesn't initialise properly once started. I'll try it again once that issue is resolved, but I suspect it will work - sorry for the wild goose chase!

**Comment by jlillis** [comment]
#177 should be resolved as of 624874237318c196b660800e586a6524cae3eaf8 - let me know if you still experience either issue on the develop branch.
