### ISSUE TITLE
Selling a vehicle is not atomic

### ISSUE THREAD

**Issue by Sharayde** [LordGolias/antistasi#183]
How to reproduce:
Put single item into valuable vehicle.
Unload to ammobox.
Open Vehicle Management.
Spam sell the vehicle a couple of times.
Stop before the unloading finishes.
Then, rinse and repeat.

If done with a highly valuable vehicle, like a T-90, you can generate huge amounts of cash.

**Comment by SomethingSimpl** [comment]
Ive tried this numerous times and wasnt able to succeed. It looks like doing this is impossible.

**Comment by LordGolias** [comment]
I had the same experience: was also not able to reproduce. Will close for now, and see if @Sharayde can give us more context.

**Comment by Sharayde** [comment]
I was using CUP, but when you unload an ammo box into a vehicle using the menu, and then spam the button to sell the vehicle, it used to not remove the vehicle, and if you did it with something absurdly expensive, you could make infinite cash. Since that was back in April, it might have been patched out already. I would see if I could recreate it myself but I'm lazy.
