### ISSUE TITLE
Loading of saves

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#186]
Hi,

We noticed that the develop branch has an issue with save loading. When you start the mission the saves do not show up in the list its empty and you can only pick New Game. 

When youre saving the game after you create a new entry all of the previous savegames suddenly show up in the list.

This is all in MP hosted from my account. Not a dedicated server.

**Comment by LordGolias** [comment]
Can't reproduce this. Any error in the log?

**Comment by LordGolias** [comment]
> Hm, havent played around with AS in a long time as it went kinda dark. Going to check now and let you know!

Yeap, hadn't much time for it. I am having time now again, so returning to it (see commit history)

**Comment by SomethingSimpl** [comment]
> 
> 
> > Hm, havent played around with AS in a long time as it went kinda dark. Going to check now and let you know!
> 
> Yeap, hadn't much time for it. I am having time now again, so returning to it (see commit history)

Sorry if I sounded rude, didn't mean it that way. Glad to hear you're back!

**Comment by SomethingSimpl** [comment]
Just checked, this seems to be resolved now.
