### ISSUE TITLE
HQ Relocation and Fast Travel

### ISSUE THREAD

**Issue by RohanTLK** [LordGolias/antistasi#2]
When relocating HQ at game-start, it only teleported Petros (none of the other HQ items). Used maintenance menu to TP the rest of the items which worked. 
We then used Fast Travel. The Fast Travel notification of 'Fast Travelling. Please wait' did not disappear. 

Upon suicide to force a TP back to HQ, the game crashed.

**Comment by LordGolias** [comment]
That is odd. I just started a new game and did the following:

1. Selected a non-default location
2. Ran 200m north
3. Fast traveled back to the HQ

Everything worked.

I also 

1. moved a HQ box 20m in any direction
2. used reset HQ

which also worked.

Can you specify which commit you are using to test the game? This is the large alpha-numeric string below the green Clone/download button.
