### ISSUE TITLE
Player stays "Incognito" when armed and near enemies

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#25]
After invading an enemy Factory I started engaging enemies. The status of Cover didn't change from "Incognito" to "Overt" even by killing multiples AIs. They never shot back.

NOTE: This was tested using the last downloadable version in Tanoa

![20170905131020_1](https://user-images.githubusercontent.com/6933497/30060743-897dae24-923c-11e7-8160-7d03ac956d8c.jpg)

**Comment by SomethingSimpl** [comment]
Hm, Iam having issues reproducing this. Could you please give more info about what exactly happened?

**Comment by Warhammer47** [comment]
As far as I checked is related to vehicles.
1 - load previous save
2 - Get military gear
3 - Retrieve civilian car from garage and get in 
4 - (Status in Incognito)
5 - Leave car with weapon on hand and status remains incognito

**Comment by Warhammer47** [comment]
I'm not being able to reproduce it again, but looks like one save game got this issue saved. New Games are not having this problem.

**Comment by SomethingSimpl** [comment]
I had this happen to me as well today. After getting out of my offroad I was stuck in the Incognito until I got on the truck again. The truck got me detected, not my weapons or armor.
