### ISSUE TITLE
Train FIA: Generic error in expression

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#26]
Pressing the "Train FIA" button in the HQ flag dialog gives "Generic error in expression".

[This is the file where the error occurs I think](https://github.com/LordGolias/antistasi/blob/266bd316e1a689cb144a9f4fd218f4d90100b6a9/Antistasi/Dialogs/HQmenu.hpp#L15)

Tried adding a semicolon, havent helped. Its beyond me unfortunately.

**Comment by SomethingSimpl** [comment]
This can be fixed by changing:

`BTN_R(2,109, "Train FIA", "Increase HR capacity and FIA skill", "[] remoteExec [""fnc_BE_buyUpgrade"", 2]");`

To:

`BTN_R(2,109, "Train FIA", "Increase HR capacity and FIA skill", "call fnc_BE_buyUpgrade;");`

**Comment by LordGolias** [comment]
The function `fnc_BE_buyUpgrade` is server side, which is why we use `remoteExec[,2]`. It is odd that it crashes with `remoteExec`. Do you have the error full message on the error (RTS file)?

**Comment by SomethingSimpl** [comment]
Yeah I thought so, but just wanted to make it work for me. I will try to provide the .rpt byt iam currently out of town. It should be reproducable easy enough though.
