### ISSUE TITLE
VCOM integration

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#3]
Hi Golias,

Couldnt get the pull requests working (add a pull request) so Iam using this as a way to ask you if its possible/viable to make the mission compatible with VCOM as far as mission related AI scripts are considered.

For example VCOM overwrites Petro's AI making him run towards combat and similar instances of incompatibility.

Thanks for this awesome fork btw!

Kind regards,

SomethingSimple

**Comment by LordGolias** [comment]
Hey @SomethingSimpl, thanks for the interest and for the suggestion. Could you point me to what VCOM is, and where can I find it?

**Comment by SomethingSimpl** [comment]
Hi @LordGolias, VCOM AI is what i would call a leading ARMA 3 FSM AI with well performing scripts and lots of work poured into it from Genesis.

https://forums.bistudio.com/forums/topic/166374-vcom-ai-v20-ai-overhaul/

It makes the AI feel more capable but in a semi-realistic-not-just-laser-accurate way.

The one flaw it has is that its rather controling meaning that missions scripted without it in its mind usually have problems such as Petros coming out to help you in battle.

I personally think it would be worth investigating a way to get it into your fork as the original devs of Antistasi have never really been interested.

I love the work you put into this as far as optimalization goes and hope you will continue caring about this fork for as long as possible! :)

P.S. Do you have any plans looking into stuff they added/changed in 1.7.5.?

**Comment by LordGolias** [comment]
Sounds cool. 

Let me check if I understand you correctly: the issue is that when antistasi is run with VCOM mod, Petros follows to battle and what else, and the expected behavior is that Petros stays still as if VCOM would not be enable.

The way to reproduce this issue is to activate VCOM mod, start a new antistasi game, and run around. Petros will follow you.

Is every statement here correct?

**Comment by SomethingSimpl** [comment]
Yes, just launch the Altis mission, run towards the nearest enemy
town/objective, try to start a fight and Petros will start running towards
the battle and engaging.

Not really sure if theres really a way to fix that in the mission scripts
alone, probably will to think of a way to integrate the VCOM script into
Antistasi with tweaks to VCOM. But not really sure as I never delved into
Arma scripting that much.

**Comment by SomethingSimpl** [comment]
Petros will not join your group and follow you btw. Its just when combat starts in a certain radius, Petros as a friendly AI unit will come towards it and engage

**Comment by LordGolias** [comment]
@SomethingSimpl thank you for the report. I was able to reproduce the issue and fix it. Petros should no longer leave its position under any circumstance.

**Comment by LordGolias** [comment]
@SomethingSimpl btw, is there any stuff added/changed in 1.7.5. that you believe is worth adding to this version?

**Comment by SomethingSimpl** [comment]
@LordGolias Actually checked what some of the devs said so far on the forums and what I got from it is:

Some fixes (probably impossible to find out what they fixed)

New UI (dont really think its that big of a deal)

Added 3 new missions (what I personally noticed is a Forest Patrol mission that popped up while playing)

So maybe just the missions? But again, I dont think its worth spending too much time on it honestly.
