### ISSUE TITLE
Compositions for AAF outposts, bases, seaports

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#32]
Hi,

What do you think about adding custom made compositions for AAF bases and outposts beyond just adding a mortar and HMG as the mission does now?

I was thinking compositions similar to CSAT hill compositions, handmade and tweaked to provide a bit more realism to the current stale "just place a bunch of soldiers/trucks/mortar/hmg/box" as well as quite a bit of challenge if the outposts were actually defensible now.

Actually could be somehow tied in to the AAF resources system as the faction could be able to build it up in preset steps e.g. "lvl1" - sandbags, "lvl2" - HESCO barriers etc.

It could provide a feeling of progression beyond the enemy just having more helicopters and tanks, help to pace the game a bit more and in my opinion add a "high-stakes" feeling to the late game.

**Comment by LordGolias** [comment]
I am all for it. There are two options for this:

1. design a random generator of compositions (e.g. sandbags at the entrance of certain buildings, etc)
2. create custom compositions for specific places.

I am not very good at doing this, so I will refrain from doing it, but I will welcome and incorporate pull requests of compositions under the format we use. Note that some already exist, check e.g. [this file](https://github.com/LordGolias/antistasi/blob/master/Antistasi/Compositions/cmpMTN.sqf) for hills.

**Comment by SomethingSimpl** [comment]
Alright! Iam on it, will try to provide a quick example before starting the main work.

**Comment by Warhammer47** [comment]
Hi everyone,
Just finished the[ compositions](https://github.com/LordGolias/antistasi/pull/68/commits/2673eefdb05eb6072d428cf116e447d7da2e5a2e#diff-76f7163bca90eee6ef6c236e3e3b31c4) of Outposts, Bases, Seaports and Airports, hope you enjoy ;)
P.S. One of the Naval Bases was not made since I suggest another location to move it (end of code).

**Comment by LordGolias** [comment]
This has been incorporated for Tanoa. @Warhammer47, do you have Altis done? I am aiming for this to be part of v0.2.

**Comment by Warhammer47** [comment]
Altis compositions are ready to go, here they are:

[locations_altis.txt](https://github.com/LordGolias/antistasi/files/1406621/locations_altis.txt)

**Comment by LordGolias** [comment]
@SomethingSimpl, is this what you had in mind? Please let us know if you have something, so it can be incorporated. Team up with @Warhammer47 if needed.
