### ISSUE TITLE
HR and FIA Money doesnt appear to get saved/loaded properly

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#35]
After saving and loading the game gives me the default values for HR and FIA Money every time.

**Comment by LordGolias** [comment]
Is this multiplayer or single player? Dedicated or not?

**Comment by SomethingSimpl** [comment]
Multiplayer, not dedicated

**Comment by LordGolias** [comment]
This has been fixed with the refactor of the saving system.
