### ISSUE TITLE
Under unknown circumstances, during unconscious, SPACE does not trigger a respawn

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#41]

**Comment by mike-187** [comment]
not sure if that helps.. but I got a lot spam log file of this stuff here when I died and couldn't respawn.
space key didn't do anything and when I hit esc / respawn I was back in HQ lying on the floor and couldn't do anything..

as said this spams the logfile:


22:22:05   Error Undefined variable in expression: _truck
22:22:05 File mission\spawns\fnc_help_meds.sqf [AS_mission_fnc_help_meds], line 184
22:22:05 Error in expression <oNumber date > _max_date) or (not alive _truck)};

waitUntil {sleep 1;
({(side _>
22:22:05   Error position: <_truck)};

waitUntil {sleep 1;
({(side _>
22:22:05   Error Undefined variable in expression: _truck
22:22:05 File mission\spawns\fnc_help_meds.sqf [AS_mission_fnc_help_meds], line 181
22:22:06 Error in expression <t alive _truck)};

waitUntil {sleep 1; (_truck distance _position < 40 and (spee>
22:22:06   Error position: <_truck distance _position < 40 and (spee>
22:22:06   Error Undefined variable in expression: _truck
22:22:06 File mission\spawns\fnc_help_meds.sqf [AS_mission_fnc_help_meds], line 270
22:22:06 Error in expression <(side _x == side_blue) and (_x distance _truck < 50)} count allUnits > 0) or _fn>
22:22:06   Error position: <_truck < 50)} count allUnits > 0) or _fn>
22:22:06   Error Undefined variable in expression: _truck

**Comment by LordGolias** [comment]
Thanks Mike. Unfortunately that was another error (already fixed, related to #55).

**Comment by LordGolias** [comment]
I think I have fixed this with 457c96f and 1c0c55def7f2cb54ad8086a56d1c91e9f026e9c9. Please confirm that this is the case.

**Comment by mike-187** [comment]
@LordGolias yes respawn works now everytime. Either with space-key or it respawns you right away.

**Comment by LordGolias** [comment]
Great. Thanks for testing @mike-187, I will close this for now, as it seems to have been fixed.
