### ISSUE TITLE
Saving game in MP does not copy to clipboard

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#52]
In SP this works as expected.

**Comment by LordGolias** [comment]
This is because [copyToClipboard](https://community.bistudio.com/wiki/copyToClipboard) only works in SP and MP if the client is server.

**Comment by mike-187** [comment]
On dedicated server I just tried to save and it didn't complete. here is the error log:
21:48:46 "[AS] Server: saving game..."
21:48:46 "[AS] Server: serializing game..."
21:48:46 "[AS] Server: serializing AAF arsenal..."
21:48:46 "[AS] Server: serializing locations..."
21:48:52 "[AS] Server: serializing fia_hq..."
21:48:52 "[AS] Server: serializing FIA arsenal..."
21:48:54 "[AS] Server: serializing persistents..."
21:48:54 Error in expression <t;
private _closest_pos = _closest call AS_location_fnc_location;
private _size >
21:48:54   Error position: <AS_location_fnc_location;
private _size >
21:48:54   Error Undefined variable in expression: as_location_fnc_location
21:48:54 File database\fnc_persistents_toDict.sqf [AS_database_fnc_persistents_toDict], line 40

**Comment by LordGolias** [comment]
@mike-187, yap, my bad :( Just pushed a fix for it with 726d6245cbf364525c4f9d4a0f23b912d6120ae0.

The problem still remains that we cannot save the string into a file (this issue)

**Comment by LordGolias** [comment]
Closing as this will be handled in #174
