### ISSUE TITLE
Supply convoy mission task is failed after player brings supply truck to village

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#53]
Greetings,
After stealing the supply truck from the AAF and bring it to the village (Lifou in this case) the task was failed since, I presume, it counted as enemy reaching the village.
Thanks,
Warhammer47

**Comment by LordGolias** [comment]
Is this the convoy mission, or the supply of meds that got intercepted?

**Comment by Warhammer47** [comment]
It's the "Attack Supply Convoy" (meds) mission
