### ISSUE TITLE
Persistent save on dedicated linux server doesnt works

### ISSUE THREAD

**Issue by highwave70** [LordGolias/antistasi#54]
Hi LordGolias,

i've read the antistasi guide from start to end.
My server is a linux dedicated, and persistent is set.

The commander menu "save/load" doesnt works, keep saying "canceled : save already in progress"
So each time i restart, we lose all progress and start from de begining.

Could mp my server if you want to make some test

Cheers

**Comment by mike-187** [comment]
Mentioned the same issue .... 
On dedicated linux server I just tried to save and it didn't complete. here is the error log:
21:48:46 "[AS] Server: saving game..."
21:48:46 "[AS] Server: serializing game..."
21:48:46 "[AS] Server: serializing AAF arsenal..."
21:48:46 "[AS] Server: serializing locations..."
21:48:52 "[AS] Server: serializing fia_hq..."
21:48:52 "[AS] Server: serializing FIA arsenal..."
21:48:54 "[AS] Server: serializing persistents..."
21:48:54 Error in expression <t;
private _closest_pos = _closest call AS_location_fnc_location;
private _size >
21:48:54 Error position: <AS_location_fnc_location;
private _size >
21:48:54 Error Undefined variable in expression: as_location_fnc_location
21:48:54 File database\fnc_persistents_toDict.sqf [AS_database_fnc_persistents_toDict], line 40

--Mike

**Comment by highwave70** [comment]
Hi Mike,

Sorry, hope that Lord will move my post in the same thread

Wave

**Comment by mike-187** [comment]
no its fine I think i did paste it to the wrong thread :)

**Comment by highwave70** [comment]
mike, my steamid : highwave70 
maybe we could help each other to debug and gives Golias any intels :)

**Comment by LordGolias** [comment]
@highwave70, thanks a lot for taking the time to report this. It was indeed an error added very recently. I just pushed a fix for it. It should work now. Could you double check please?
