### ISSUE TITLE
revive option is gone. only healing possible.

### ISSUE THREAD

**Issue by mike-187** [LordGolias/antistasi#56]
Revive option is gone. Only healing possible. Or is that now intended?

Could it be that the Revive script is missing?

I use non-ace version.

I saw this closed ticket and there still was an entry in Antistasi/Revive/medical.sqf which is gone?
https://github.com/LordGolias/antistasi/issues/23

**Comment by LordGolias** [comment]
In non-ACE, healing a fallen unit revives it. Would you expect this to be different? How come? An action to revive the unit (i.e. split the revive in healing+revive?)

**Comment by mike-187** [comment]
ok so its intended.. I thought there was a revive menu in the past. I asked cause when I shot enemies... then try to revive so they surrender... they start shooting again at me. Maybe I missed there something. Maybe they surrender other way.. will test more.

**Comment by LordGolias** [comment]
ATM if you revive enemies, they do not surrender. That would be cool though. What do you think?

**Comment by mike-187** [comment]
that would be cool :) but maybe a thing for the future ... so actually the way you have it now is just fine. So you can close this issue. Thanks.
