### ISSUE TITLE
Button dismiss AI is not working. 

### ISSUE THREAD

**Issue by mike-187** [LordGolias/antistasi#57]
Button dismiss AI is not working.  AI does not react or any logfile entry. It just doesn't work.

--Mike

**Comment by mike-187** [comment]
@LordGolias cool works now. Are you suppose to get some cash back when you dismiss AI? just askin as its like that in the original antistasi. thx.

**Comment by LordGolias** [comment]
Currently, you [get half of the price](https://github.com/LordGolias/antistasi/blob/0f29a8b858f1cb5c4b02ef249313ff7308842af6/Antistasi/fia_recruitment/fnc_dismissFIAunits.sqf#L70)
