### ISSUE TITLE
AAF mortar AI invincible.

### ISSUE THREAD

**Issue by mike-187** [LordGolias/antistasi#59]
I can't kill AAF mortar AI... the one using it. 
You have to shoot the mortar itself until its destroyed. Then the AI disembarks and you can kill it then. 
So basically if AI is mounted to a mortar you can not kill it. (tested on dedicated server)

--Mike

**Comment by LordGolias** [comment]
With or without ACE? :D

**Comment by mike-187** [comment]
without :)

**Comment by LordGolias** [comment]
Unfortunately I am not able to reproduce this. 

Specifically, without any mods:
1. started a new mission in Altis
2. went to the hill next to the default HQ (that has a mortar)
3. shoot the mortar on sight. It felt unconscious on the first shoot, died on the second to the head.

It may be that the mortars are initialized differently on each location. Could you specify which mortar was invincible?

**Comment by mike-187** [comment]
I think thats the same mortar.. I also started new game at Altis and and went up north for the hilltop there.
Just tested in SP and its ok there. Will test more maybe its dedicated issue only... will also try other hilltops locations and will test SP/ local host MP / dedicated versions difference.

**Comment by mike-187** [comment]
ok no idea but I cannot reproduce it anymore. sorry for the confusion maybe it was a glitch. can be closed for now.
