### ISSUE TITLE
Respawn, Persistence, Map Info

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#6]
Downloaded the latest version from GitHub yesterday and had a couple of hours of playing (COOP with 1 friend, normal HOST not DEDICATED)

1. Respawn appears to be INSTANT instead of BASE. Or rather, its set to BASE in description.ext but for some reason every time we got killed it respawned us on the spot we died instantly.

2. Tried persistent saving, location was saved but the arsenal was wiped clean for some reason, not really sure what couldve gone wrong. FIA HQ marker on the map doesnt move on map load. Actually the whole saving except for the location doesnt appear to work correctly.

3. When we captured a base and it gave us the messages about AAF Counter attack it didnt say time but: Scalar NAN.

4. Map Info doesnt appear to be working. Nothing happens when you select it from the action menu.

**Comment by LordGolias** [comment]
:/ Interesting. Do you have the log from that game on your computer that you could share?

**Comment by SomethingSimpl** [comment]
Good morning,

Actually we were more of playtesting than just playing a campaign so no important data was lost, these are just things we noticed in a couple of hours of testing.

I will provide the logs ASAP. Tried all twice on two different computers just to be sure and all of the script errors are there.

Thanks for the quick reply btw!

**Comment by SomethingSimpl** [comment]
This is the .rpt, couldnt find the old one so I tried to reproduce it all.

This time around when I captured a base it didnt give me that weird message, it said 10 minutes correctly.

- The first thing I tried was to load a the persistent save. It loaded the location correctly but once again the marker on the map stayed on the default position and weapons werent available.
- Then I tried Map Info, didnt work. Gave an error message about a variable being empty.
- After that I teleported to a base, captured it.
- Teleported back and put new weapons into the crate.
- Saved.

[Arma3_x64_2017-07-29_10-20-04.zip](https://github.com/LordGolias/antistasi/files/1184798/Arma3_x64_2017-07-29_10-20-04.zip)

**Comment by LordGolias** [comment]
Well, @SomethingSimpl, thank you and your friend very much for doing that! I will go through them and get back here.

**Comment by LordGolias** [comment]
I am confident that I have fixed the city info issue (4) with 9716cbc. The persistent problem (2) is probably fixed, but testing is required. I addressed problem (1) but we also need testing. Problem (3) I have not touched yet.

**Comment by SomethingSimpl** [comment]
Thanks for the prompt fixes! This is awesome. Going to go through it and report back :)

If youd like to play with us a bit sometimes, feel free to add me on Steam, names the same as here but with an -e at the end.

**Comment by SomethingSimpl** [comment]
Hi,

The city info issue is fixed. Persistance still acting the same way, not saving weapons in crates. Number 1 is fixed as well.

**Comment by LordGolias** [comment]
Thanks a lot @somethingsimpl for the testing and report. 

I will have no access to a windows until friday so I will not be able to work on the persistent issue until then.

It is an interesting issue. It was a recent commit that broke it since I played a recent version and it was fine. :/

**Comment by LordGolias** [comment]
I just pushed a major update to master. Do not know exactly which commit fixed this, but I tested in both SP and MP and the issue is fixed. Let me know if you do not agree with this and we re-open it.
