### ISSUE TITLE
We use RHS VDV (elite RU) for AAF, we should use VV (paramilitar)

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#60]

**Comment by StefArma** [comment]
I didn't worked on templates. So i've no idea why they choose VDV.. nor i'm expert about RHS factions. Just to understand your question, are you looking for someone to make a template with VV instead of VDV?

**Comment by StefArma** [comment]
Actually i might have found a reason, there isn't any group composition for VV.. while there are for VDV

**Comment by LordGolias** [comment]
That is a good point. I am closing this as won't fix. We may re-visit the issue of different factions later though :)
