### ISSUE TITLE
Building locations menu doesnt works

### ISSUE THREAD

**Issue by highwave70** [LordGolias/antistasi#61]
When i press Y,  Buildings Options, Manage Locations

I select position for any of the building list (roadblock, watchpost, camp), the vehicle spawn and i send it to the map position.

Then nothing happened, even after waiting 1hour. Worst, if i leave the server and get back, the mission has gone, but i cant build anymore telling me that "there is a building in progress"

You can test on my server 149.202.87.147, modset : ACE/CBA/TFAR

cheers

**Comment by LordGolias** [comment]
Thank you for the report. I will investigate and try to fix it.

**Comment by LordGolias** [comment]
I have fixed this in `develop`, and tested for the roadblock. Still needs testing for the other 2.

**Comment by LordGolias** [comment]
Working for `camp`. Only need to test `minefield` (not working yet) and `watchpost`.

**Comment by LordGolias** [comment]
This is now fixed.
