### ISSUE TITLE
Civilian workers despawned

### ISSUE THREAD

**Issue by highwave70** [LordGolias/antistasi#62]
Dont know if it is really a bug, let you judge as there is no really documentation about it : 

All factory / power plant civilian workers despawned in already controled area, so now i can't power any cities in this sector. As i put some guarison in those places, i can't believe that there were killed.

I read in the official anstasi guide that if all civilian workers are killed power plant dont works any more, but it dont explain if civilian workers will respawn later after 1h, 1day, 1week ... maybe an idea to go further (cost to repopulate factories/power plant)

cheers

**Comment by StefArma** [comment]
Hello,

what do you mean by "despawned"? 
When you leave an area, everyone despawn, when you go back (there is a radius of 1km depending on settings around you and other specific units) they should respawn. 

In official antistasi ofc if workers get killed they won't repsawn unless you "Rebuild" with commander menu

**Comment by highwave70** [comment]
Hi StefArma,

Well i saw the civilian workers spawn just after conqueer the power plant, and i put some guarison in place. Then when i reach the power plant after disconnect/reconnect, there is only my guarison but no more civilan workers.

Edit : I just try to remove the guarison and now civilian workers are spawning normaly ... dont know if its a bug or not, let LordGolias decide.

**Comment by LordGolias** [comment]
@highwave70, thank you for this report. At what time of the day did you observed that? Workers only spawn during the day. 

Is there any error on the log referring to that? If not, then it is a bug :)

**Comment by LordGolias** [comment]
I have been testing and I am not able to reproduce this anymore. I think that there was an error that was meanwhile fixed. I can see civilian workers when FIA controls e.g. a factory.
