### ISSUE TITLE
On dedicated server / recruit AI doesn't show how much they cost.

### ISSUE THREAD

**Issue by mike-187** [LordGolias/antistasi#67]
On dedicated server / recruit AI doesn't show how much the cost.

![image](https://user-images.githubusercontent.com/31815435/31335669-d374f542-acf3-11e7-84c1-13713f651338.png)

Non-ace. Tested with vanilla and CUP mod.

**Comment by LordGolias** [comment]
Thanks mike! I believe that this has been fixed on `initialization` branch. (other more important bugs may be present there though.

**Comment by mike-187** [comment]
I see... i'd like to test but didnt manage to get other branches to run at all yet... missing files errors or the mission doesnt initialize. Maybe its just me... i tried to just download one branch or merge/overwrite with newer branches. Is there a step i am missing?

**Comment by LordGolias** [comment]
Yeap, my bad. Had no access to Windows so pushed some mistakes. It should be fixed now.

**Comment by mike-187** [comment]
this has been fixed on init branch.
