### ISSUE TITLE
Petros attacks player in new game against NATO (init/compositions branch)

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#71]
When I started a new game with NATO as the enemy and CSAT as the rebellion supporter I got killed by Petros in like 10 seconds. He was carrying and used a NATO weapon.

**Comment by LordGolias** [comment]
> You shall not rebel against NATO!!

yeah, it is an error. Only in MP right? I will need to understand what is happening. Could you post the log so we can see what is the initialization steps (no windows this weekend)?

**Comment by LordGolias** [comment]
It should be fixed in initialization (and init/* branches). Can you confirm?

**Comment by LordGolias** [comment]
I tested in SP, MP and dedicated and this no longer happens in branch initialization. Thanks!
