### ISSUE TITLE
Can't access options from the Map Board, Flag Pole and Arsenal in the HQ (init/compositions branch)

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#72]
After starting a New Game and choosing AAF as the enemy, I couldn't use any of the HQ options/actions except Mission Request from Petros.
Tested with ACE mod

**Comment by LordGolias** [comment]
Fixed in 635b705f5ad81bca0f04cd5ca4869f454ac0fa04. Thanks!
