### ISSUE TITLE
Town is conquered by FIA but the "t" marker doesn't change (master)

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#73]
After conquering a Town through FIA surpassing the AAF support, the "t" letter marker doesn't change and a flagpole appears in the position of the Town marker

**Comment by LordGolias** [comment]
The flag pole is a bug that has been fixed in `initialization` branch. The `t` letter not changing: did you wait for the next "income" for FIA? The city side only formally changes when there is an income.
