### ISSUE TITLE
Credits Barbolani missing

### ISSUE THREAD

**Issue by StefArma** [LordGolias/antistasi#74]
https://github.com/LordGolias/antistasi/blob/2b0e040c65c4c3797cfb3e939971cf87c45682dd/Antistasi/briefing.sqf#L138

I see all this old names, but i think here is missing the main one.. I understand this code deeply changed.. however i think that the  concept behind this mission is still Barbolani one.

**Comment by LordGolias** [comment]
I agree. Can you do that? Thank also you and @Warhammer47 and @SomethingSimpl for testing and ideas. 

In the long run, I would like to have an intro cut with the people involved.

**Comment by LordGolias** [comment]
Closed by e9b7856a31fb829ff3cc3fcfa3753a1220d6e6d3.
