### ISSUE TITLE
Test branch develop

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#78]
I have merged the work we have been doing in the past 15 days or so into a common branch "develop". This branch contains 3 new features:

* guerrilla can be played on any side (blue/red) against any faction (AAF/CSAT/NATO)
* players can now buy traits (e.g. medic)
* custom compositions on Tanoa locations by @Warhammer47

This branch is feature frozen and requires testing before being merged to master. Once this branch is merged, a new steam version can come out.

**Comment by mike-187** [comment]
Dedicated server: Mission does not initialize at all. The side menu does not appear. U only get spawned to the default location with no assets.

**Comment by LordGolias** [comment]
lol :/. Thanks. Do you have the log @mike-187?

**Comment by mike-187** [comment]
yea its here: https://pastebin.com/6NEL75nh

**Comment by mike-187** [comment]
```

ariable [toLower _key, _value, _isGl>
14:32:19   Error position: <setVariable [toLower _key, _value, _isGl>
14:32:19   Error Reserved variable in expression
14:32:19 File dictionary\fnc__set.sqf [DICT_fnc__set], line 31
14:32:19 "DICT:get([1813928: empty.p3d,""""]):ERROR: invalid key"
14:32:19 Error in expression <nary" exitWith {}; 
};
if not (typeName _dictionary == "OBJECT") exitWith {
diag>
14:32:19   Error position: <_dictionary == "OBJECT") exitWith {
diag>
14:32:19   Error Undefined variable in expression: _dictionary
14:32:19 File dictionary\fnc__set.sqf [DICT_fnc__set], line 28

```

also got this when loggin off and back in when the serve is running.. maybe there is a hint.

**Comment by LordGolias** [comment]
@mike-187, I just pushed a a fix to this. I tested in SP, MP and dedicated that it works.

**Comment by LordGolias** [comment]
Loading game still not working.

**Comment by mike-187** [comment]
thanks @LordGolias yes it works now. The new game menu appears now. Only side affect is that the player swims in the water at 0000/0000 location.. while in the 'new game menu' but thats ok ;)

When I rejoin the server. All funktions are gone. no Y key or any other interactions are possible with the base assets. I don't see anything unusual in the log yet. But will check and attach the log.

Cannot test load / save game yet as the join in progress is not working. ;)

**Comment by LordGolias** [comment]
Thanks mike! 

2 and 3 should be fixed now.

In respect to 1: what do you mean with rejoin? Do you mean start dedicated and

1. Enter, 
2. select side and start game, 
3. exit, 
4. enter again

OR

1. Enter
2. exit
3. enter again?

**Comment by mike-187** [comment]
Yes i meant the 1st case. (1-4).

**Comment by LordGolias** [comment]
The issue 1 is now also fixed, @mike-187. 

I screwed up the branch initialization, and for that reason now created a new branch called [`develop`](https://github.com/LordGolias/antistasi/tree/develop), in line with [gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) branching model.
