### ISSUE TITLE
Debug/init.sqf is called by client

### ISSUE THREAD

**Issue by JohnnyDeeee** [LordGolias/antistasi#8]
### My setup:
- Latest arma 3 game/server version
- Dedicated server (setup using TADST)
- Client running on the same pc as the server
- Antistasi (LordGolias edit, master branch) running on Altis
- Default mission parameters

### What happend:
During the start of the mission (before creating/loading a game) the following error appears:

> "[AS] Error: Server-only script debug/init.sqf called "

I'm not sure if this affect the gameplay, but since it is labeled as an 'error' i thought why not just create an issue for it.

### Steps to reproduce:

1. Start a **dedicated** server
2. Load the Antistasi mission (Altis)
3. Look in your client's `.rpt` and notice the error qouted above

**Comment by LordGolias** [comment]
I already fixed this in one of the commits. :) Thanks for the report!
