### ISSUE TITLE
Rebelling against West changes to East after load

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#89]
Started a new game rebelling against the West (NATO).
Saved the game.
Loaded the game and noticed that Petros now carries a AAF weapon and I'm now rebelling against AAF with NATO as my supporter.

ARMA 3 SAVE LOG
https://pastebin.com/SUEL1S0K

ARMA 3 LOAD LOG
https://pastebin.com/xr0gunN9

**P.S. Tested with ACE in DEVELOP branch in MP**

**Comment by LordGolias** [comment]
Are you sure this is master branch? In master we cannot change sides. Maybe develop?

**Comment by Warhammer47** [comment]
Gonna check now

**Comment by Warhammer47** [comment]
CONFIRMATION: It persists in the MASTER branch in MP

**Comment by LordGolias** [comment]
??? in master branch you cannot change sides... what do you mean?

**Comment by Warhammer47** [comment]
I don't change side, the game simply changes it self somewhere between Save game and Load game. I can replicate and send the logs
