### ISSUE TITLE
Defend Resource Task: Only UAV comes

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#93]
After taking a resource and receive a Defend task just a UAV appeared in the area, is it normal in the begging of the game since AAF has few money in their funds? This is the respective log:

**P.S. Tested with ACE in DEVELOP branch in MP**

START LOG CODE:

[_origin, _position, _grupoheli, _group] call AS_tactics_fnc_>
23:38:50   Error position: <_grupoheli, _group] call AS_tactics_fnc_>
23:38:50   Error Undefined variable in expression: _grupoheli
23:38:50 File fnc_spawnAirAttack.sqf [AS_fnc_spawnAirAttack], line 39
23:38:50 "[AS] Error: O Alpha 2-3:1 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:2 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:3 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:4 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:5 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:6 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:7 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 "[AS] Error: O Alpha 2-3:8 was initialized without side"
23:38:50 "[AS] Error: O Alpha 1-6:1 was initialized with invalid side 'UNKNOWN'"
23:38:50 Error in expression <_vehicles pushBack _pad;
private _wp0 = _crew_group addWaypoint [_landing_positi>
23:38:50   Error position: <_crew_group addWaypoint [_landing_positi>
23:38:50   Error Undefined variable in expression: _crew_group
23:38:50 File tactics\fnc_heli_disembark.sqf [AS_tactics_fnc_heli_disembark], line 11
23:39:05 "[AS] 2: spawn 'defend_location_as_resource_6' finished state 'spawn'"
23:39:05 "[AS] 2: spawn 'defend_location_as_resource_6' started state 'run'"
23:39:08 No speaker given for 
23:39:12 "[AS] Server: scheduler_fnc_execute(AS_movement_fnc_sendAAFroadPatrol):"
23:39:12 "Worker 2: 20.3234"
23:39:16 "[AS] 2: new spawn 'AAFroadPatrol'"
23:39:16 "[AS] Server: scheduler_fnc_execute(AS_spawn_fnc_execute):"
23:39:16 "Worker 2: 20.7158"
23:39:16 "[AS] Error: spawn_fnc_execute: spawn 'AAFroadPatrol' does not exist"
23:39:16 mainturret - unknown animation source mainturret
23:39:16 maingun - unknown animation source maingun
23:39:16 leg_01 - unknown animation source fold_legs
23:39:16 leg_02 - unknown animation source fold_legs
23:39:16 leg_03 - unknown animation source fold_legs

END LOG CODE

**Comment by LordGolias** [comment]
Closed as duplicated of #85.
